HOSTNAME = "k3s"
BOX_NAME = "ubuntu/jammy64"
BOX_VERSION = "20231012.0.0" # 20231018.0.0 broke kustomize install script.
IP_ADDRESS = "192.168.56.20"
RAM_MB = "4096"
CPU_COUNT = 4
LOCAL_SETTINGS_PATH = "etc/custom_vagrantfile_settings.rb"

# Checks if LOCAL_SETTINGS_PATH exists before attempting to load it.
if File.file?(LOCAL_SETTINGS_PATH) then
  load LOCAL_SETTINGS_PATH
end

Vagrant.configure("2") do |config|
  config.vm.box = BOX_NAME
  config.vm.box_version = BOX_VERSION
  config.vm.network "private_network", ip: IP_ADDRESS
  config.vm.hostname = HOSTNAME
  config.vm.provider "virtualbox" do |vb|
    vb.memory = RAM_MB
    vb.cpus = CPU_COUNT
  end

  # On Windows hosts, sometimes it freezes at the first connection attempt.
  # Giving it 20 minutes helps but it may not solve the issue entirely.
  # If it times out, try again with 'vagrant destroy -f && vagrant up'.
  config.vm.boot_timeout = 1200

  config.vm.provision "shell", inline: <<-SHELL
    # Install some useful packages.
    apt-get -y install htop nano vim
    apt-get -y update
    apt-get -y upgrade

  SHELL

  config.vm.provision "shell", path: "../shared/buildah_install.sh"
  config.vm.provision "shell", path: "../shared/k3s_install.sh"

  # Ensure that updates that require a restart are properly applied.
  config.vm.provision :reload
end
