HOSTNAME = "k3s"
BOX_NAME = "ubuntu/jammy64"
BOX_VERSION = "20240207.0.0" # 20231018.0.0 broke kustomize install script.
IP_ADDRESS = "192.168.56.20"
RAM_MB = "4096"
CPU_COUNT = 4

Vagrant.configure("2") do |config|
  config.vm.box = BOX_NAME
  # config.vm.box_version = BOX_VERSION
  config.vm.network "private_network", ip: IP_ADDRESS
  config.vm.hostname = HOSTNAME
  config.vm.provider "virtualbox" do |vb|
    vb.memory = RAM_MB
    vb.cpus = CPU_COUNT
  end

  # On Windows hosts, sometimes it freezes at the first connection attempt.
  # Giving it 20 minutes helps but it may not solve the issue entirely.
  # If it times out, try again with 'vagrant destroy -f && vagrant up'.
  config.vm.boot_timeout = 1200

  config.vm.provision "shell", inline: <<-SHELL
    apt-get -yqq update

    # Install some useful packages.
    apt-get -yqq install gh htop nano policycoreutils vim whois zip
    apt-get -yqq install apt-transport-https ca-certificates gnupg curl sudo
    apt-get -yqq install build-essential python3-pip jq glances podman

    apt-get -yqq upgrade

    su - vagrant -c "python3 -m pip install pylint mypy --user"

  SHELL

  # Ensure that updates that require a restart are properly applied.
  config.vm.provision :reload

  # Install Shared Content.
  config.vm.provision "shell", path: "../shared/k3s.sh"
  config.vm.provision "shell", path: "../shared/kustomize.sh"
  config.vm.provision "shell", path: "../shared/helm.sh"
  config.vm.provision "shell", path: "../shared/homebrew.sh"
end

# Load additional .rb files in ./etc/, if present.
Dir["./etc/*.rb"].each{|rubyfile| load rubyfile}
