HOSTNAME = "awx"
BOX_NAME = "ubuntu/jammy64"
BOX_VERSION = "20231012.0.0" # 20231018.0.0 broke kustomize install script.
IP_ADDRESS = "192.168.56.10"
NODE_PORT = 30080
RAM_MB = "4096"
CPU_COUNT = 4

Vagrant.configure("2") do |config|
  config.vm.box = BOX_NAME
  config.vm.box_version = BOX_VERSION
  config.vm.network "private_network", ip: IP_ADDRESS
  config.vm.hostname = HOSTNAME
  config.vm.provider "virtualbox" do |vb|
    vb.memory = RAM_MB
    vb.cpus = CPU_COUNT
  end

  # On Windows hosts, sometimes it freezes at the first connection attempt.
  # Giving it 20 minutes helps but it may not solve the issue entirely.
  # If it times out, try again with 'vagrant destroy -f && vagrant up'.
  config.vm.boot_timeout = 1200

  # Copy Kustomization Config file
  config.vm.provision "file", source: "kustomization.yaml", destination: "/home/vagrant/kustomization.yaml"
  config.vm.provision "file", source: "awx.yaml", destination: "/home/vagrant/awx.yaml"

  config.vm.provision "shell", inline: <<-SHELL
    # Install some useful packages.
    apt-get -yqq install buildah gh htop nano policycoreutils vim whois zip
    apt-get -yqq update
    apt-get -yqq upgrade

  SHELL

  # Ensure that updates that require a restart are properly applied.
  config.vm.provision :reload

  # Install K3s/Kustomize/AWX
  config.vm.provision "shell", path: "../shared/k3s.sh"
  config.vm.provision "shell", path: "../shared/kustomize.sh"
  config.vm.provision "shell",
    path: "awx_install.sh",
    env: {"IP_ADDRESS" => IP_ADDRESS, "NODE_PORT" => NODE_PORT}
end

# Load additional .rb files in ./etc/, if present.
Dir["./etc/*.rb"].each{|rubyfile| load rubyfile}
