HOSTNAME = "awx"
OS_IMAGE = "ubuntu/jammy64"
IP_ADDRESS = "192.168.56.10"
NODE_PORT = 30080
RAM_MB = "4096"
CPU_COUNT = 4

Vagrant.configure("2") do |config|
  config.vm.box = OS_IMAGE
  config.vm.network "private_network", ip: IP_ADDRESS
  config.vm.hostname = HOSTNAME
  config.vm.provider "virtualbox" do |vb|
    vb.memory = RAM_MB
    vb.cpus = CPU_COUNT
  end

  # On Windows hosts, sometimes it freezes at the first connection attempt.
  # Giving it 20 minutes helps but it may not solve the issue entirely.
  # If it times out, try again with 'vagrant destroy -f && vagrant up'.
  config.vm.boot_timeout = 1200

  # Copy Kustomization Config file
  config.vm.provision "file", source: "kustomization.yaml", destination: "/home/vagrant/kustomization.yaml"
  config.vm.provision "file", source: "awx.yaml", destination: "/home/vagrant/awx.yaml"

  config.vm.provision "shell", inline: <<-SHELL
    # Install some useful packages.
    apt-get -y install htop nano vim
    apt-get -y update
    apt-get -y upgrade

  SHELL

  # Ensure that updates that require a restart are properly applied.
  config.vm.provision :reload

  config.vm.provision "shell", path: "../shared/k3s_install.sh"
  config.vm.provision "shell",
    path: "awx_install.sh",
    env: {"IP_ADDRESS" => IP_ADDRESS, "NODE_PORT" => NODE_PORT}
end
